name: Conventional Commit on Push

on: [push]

jobs:
  conventional-commit-checker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: '16.x'
      - run: cd .github/conventionalcommits && npm install
      - run: cd .github/conventionalcommits && npm run build --if-present

      - name: conventional-commit-checker
        id: hello
        uses: ./.github/conventionalcommits
